# Generated by Django 4.2.7 on 2023-11-06 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('uf', models.CharField(choices=[('SP', 'São Paulo'), ('RJ', 'Rio de janeiro'), ('MG', 'Minas Gerais'), ('ES', 'Espirito Santo')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contato',
            options={'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AddField(
            model_name='contato',
            name='estado_civis',
            field=models.CharField(choices=[('S', 'Solteiro'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viúvo')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascença'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.IntegerField()),
                ('numero', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('RES', 'Residencial'), ('COM', 'Comercial'), ('REC', 'Recado')], max_length=3)),
                ('EhWhatsApp', models.BooleanField(verbose_name='Tem WhatsApp ?')),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgendaApp.contato')),
            ],
        ),
        migrations.AddField(
            model_name='contato',
            name='interesses',
            field=models.ManyToManyField(to='AgendaApp.interesse'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgendaApp.cidade'),
        ),
    ]
